# Generated by Django 5.1.5 on 2025-03-25 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestataire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projet.project'),
        ),
        migrations.AddField(
            model_name='decaissement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decaissements', to='projet.project'),
        ),
        migrations.AddField(
            model_name='citizenreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projet.project'),
        ),
        migrations.AddField(
            model_name='projectlocation',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projet.project'),
        ),
    ]
